theme: jekyll-theme-minimal
title: Hydrogen Projects Map
description: This website demonstrates how to easily publish and display an interactive map made with Folium. It features some hot spots around Ithaca, NY.
